### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by SkyeHoefling** [ahoefling/CircleButtonMenu#2]
We really need a sample project and a few screenshots to show off the power of the control

**Comment by montehansen** [comment]
I agree, I don't get what the CircleButtonMenu does. I added it to my page and nada.

**Comment by SkyeHoefling** [comment]
I added a sample project and a gif to the main readme of what the project does.

![demo](https://github.com/ahoefling/CircleButtonMenu/blob/91d6523c8454e10cfcc3d33b73b25eff33534733/demo.gif?raw=true)
